import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Leaf, Globe, Zap, BarChart3, ArrowRight, ShieldCheck, CheckCircle2 } from 'lucide-react';

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background selection:bg-primary selection:text-primary-foreground">
      {/* Hero Section */}
      <header className="relative overflow-hidden pt-20 pb-16 md:pt-32 md:pb-32">
        <div className="container mx-auto px-6 relative z-10">
          <div className="max-w-4xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary mb-6 animate-fade-in">
              <Leaf className="w-4 h-4" />
              <span className="text-sm font-medium tracking-wide">Version 2.0 Now Live</span>
            </div>
            <h1 className="text-6xl md:text-8xl font-headline font-bold mb-8 leading-[1.1] animate-fade-in [animation-delay:0.1s]">
              Measure Smarter.<br />
              <span className="text-primary">Live Greener.</span>
            </h1>
            <p className="text-xl md:text-2xl text-muted-foreground mb-10 max-w-2xl leading-relaxed animate-fade-in [animation-delay:0.2s]">
              FootprintIQ is your AI-powered carbon intelligence platform. Understand your impact with precision and receive personalized pathways to a sustainable lifestyle.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 animate-fade-in [animation-delay:0.3s]">
              <Button asChild size="lg" className="h-14 px-8 text-lg font-medium rounded-full">
                <Link href="/assessment">
                  Start Your Assessment
                  <ArrowRight className="ml-2 w-5 h-5" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="h-14 px-8 text-lg font-medium rounded-full glass border-white/10 hover:bg-white/5">
                <Link href="/dashboard">View Demo Dashboard</Link>
              </Button>
            </div>
          </div>
        </div>
        
        {/* Background blobs */}
        <div className="absolute top-0 right-0 -translate-y-1/2 translate-x-1/4 w-[600px] h-[600px] bg-primary/20 rounded-full blur-[120px] pointer-events-none" />
        <div className="absolute bottom-0 left-0 translate-y-1/2 -translate-x-1/4 w-[500px] h-[500px] bg-accent/10 rounded-full blur-[100px] pointer-events-none" />
      </header>

      {/* Features Grid */}
      <section className="py-24 border-t border-white/5">
        <div className="container mx-auto px-6">
          <div className="grid md:grid-cols-3 gap-12">
            <FeatureCard
              icon={BarChart3}
              title="Intelligence Hub"
              description="Visualize your carbon footprint across 5 key categories with high-fidelity charts and trend analysis."
            />
            <FeatureCard
              icon={Zap}
              title="AI Sustainability Advisor"
              description="Receive context-aware recommendations generated by Google Gemini based on your unique lifestyle."
            />
            <FeatureCard
              icon={Globe}
              title="Impact Forecast Studio"
              description="Simulate lifestyle changes in real-time and see projected annual carbon and cost savings."
            />
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-24 bg-card/50">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-4xl font-headline font-bold mb-16">The Journey to Net Zero</h2>
          <div className="grid md:grid-cols-4 gap-8">
            <Step number="01" title="Assess" description="Complete our intelligent 5-step lifestyle assessment." />
            <Step number="02" title="Analyze" description="AI identifies your primary emission contributors." />
            <Step number="03" title="Act" description="Follow your personalized 30-day carbon action plan." />
            <Step number="04" title="Improve" description="Track progress and earn eco-warrior achievements." />
          </div>
        </div>
      </section>

      {/* CTA Footer */}
      <section className="py-32">
        <div className="container mx-auto px-6">
          <div className="glass rounded-[3rem] p-12 md:p-24 text-center relative overflow-hidden">
            <div className="relative z-10">
              <h2 className="text-4xl md:text-6xl font-headline font-bold mb-8">Ready to join the movement?</h2>
              <p className="text-xl text-muted-foreground mb-12 max-w-2xl mx-auto">
                Join 10,000+ individuals tracking their journey to a sustainable future with FootprintIQ.
              </p>
              <Button asChild size="lg" className="h-16 px-12 text-xl font-medium rounded-full bg-white text-black hover:bg-white/90">
                <Link href="/assessment">Join FootprintIQ Today</Link>
              </Button>
            </div>
            <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-primary/20 via-transparent to-accent/10 pointer-events-none" />
          </div>
        </div>
      </section>

      <footer className="py-12 border-t border-white/5 text-center text-muted-foreground">
        <div className="container mx-auto px-6">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Leaf className="w-5 h-5 text-primary" />
            <span className="font-headline font-bold text-lg text-foreground">FootprintIQ</span>
          </div>
          <p>© 2024 FootprintIQ Carbon Intelligence. Built for a better planet.</p>
        </div>
      </footer>
    </div>
  );
}

function FeatureCard({ icon: Icon, title, description }: { icon: any, title: string, description: string }) {
  return (
    <div className="group p-8 rounded-3xl border border-white/5 bg-card hover:border-primary/50 transition-all duration-300">
      <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center text-primary mb-6 group-hover:scale-110 transition-transform">
        <Icon className="w-6 h-6" />
      </div>
      <h3 className="text-2xl font-headline font-bold mb-4">{title}</h3>
      <p className="text-muted-foreground leading-relaxed">{description}</p>
    </div>
  );
}

function Step({ number, title, description }: { number: string, title: string, description: string }) {
  return (
    <div className="flex flex-col items-center">
      <div className="text-5xl font-headline font-black text-primary/20 mb-4">{number}</div>
      <h3 className="text-xl font-bold mb-2">{title}</h3>
      <p className="text-muted-foreground">{description}</p>
    </div>
  );
}